### ISSUE TITLE
about blog system name

### ISSUE THREAD

**Issue by pea3nut** [pea3nut/a-blog-interface#2]

**Comment by pea3nut** [comment]
著名游戏/动漫公司KEY，在2015年推出一个原创动画[Charlotte](https://zh.wikipedia.org/wiki/Charlotte_\(動畫\))（中文译名：夏洛特）。

Charlotte在故事中为每七十五年接近地球一次的长期彗星，Charlotte接近时会向地球释放神秘粒子，令吸入者获得特殊能力。但是这对于吸入者可能并不是好事，相反可能会带来灾祸。而故事的主线则是主角一行人帮助各个吸入者剥离超能力。

其中故事中，主角一行人属于星之海学园（星ノ海学園／ほしのうみがくえん Hoshinoumi-gakuen ）学生会。

于是，组织名可以为`Hoshinoumi`，而整个项目为`Charlotte`，项目各个模块为作品中各个登场角色名字。

---

说起来，这部动漫差不多算是我追动漫的开始，然后接下来愈演愈烈最终变成了一名死宅。

**Comment by lidongjies** [comment]
看了一下百科，登场人物挺多的，够用了。我看的第一部动漫是数码宝贝。

**Comment by pea3nut** [comment]
我看的第一部貌似是魔卡少女樱。。。但是正式开始一步步走向死宅确实是从Charlotte开始。

我觉得Charlotte和程序员很像。拥有着强大的力量，但是拥有过高的力量必须要有足够的觉悟，否则只会给自己带来灾祸。

当然，用这个有个缺点是组织名略难打，而Charlotte已经有github用户在使用了，应该无法创建成组织。

参考资料：
- https://zh.moegirl.org/Charlotte
- https://zh.wikipedia.org/wiki/Charlotte_(動畫)

**Comment by pea3nut** [comment]
还有一个想法。

《吹响！上低音号》，一部轻小说，著名动画制作公司东京动画在2015年将其改编动画化。

- https://zh.wikipedia.org/wiki/吹響吧！上低音號
- https://zh.moegirl.org/吹响!上低音号

相当不错的动漫，我曾经发过的博客[丽奈：我想成为特别的人 | 写于北京实习3周之际](http://blog.pea3nut.com/e872)结尾的引用就是来源于此。

在动漫中女主一行人隶属于北宇治高中管乐团，从事着演奏活动（交响乐）。

于是组织名可以使用“北宇治”，各个仓库名为各个交响乐器，比如：上低音号、双簧管、低音提琴、大号

顺便还可以低音乐器是前端，高音是后端hhhh

**Comment by pea3nut** [comment]
北宇治没找到相关英文，きたうじ转成罗马音是kitauji

> 北宇治高中（北宇治高校（きたうじこうこう））

读音可以去 translate.google.com 听，拼音大概是ki ta wu ji

**Comment by lidongjies** [comment]
我还是比较喜欢第一个想法的，可惜了。fate stay night 中的七个Servant如何？

**Comment by pea3nut** [comment]
https://github.com/Hoshinoumi/Charlotte
